// ------------------------------
// GENERATED BY GOOGLE GEMINI 3.0
// ------------------------------

// --- Configuration ---
const TAG = "v0.1.3";
const RELEASE_NAME = "Version 0.1.3";
const RELEASE_NOTES = "Publishing to JSR";
// ---------------------

async function runCommand(command: string, args: string[]): Promise<string> {
  const commandString = `${command} ${args.join(" ")}`;
  console.log(`\n$ ${commandString}`);

  const cmd = new Deno.Command(command, {
    args,
    stdout: "piped",
    stderr: "piped",
  });

  const { code, stdout, stderr } = await cmd.output();

  const stdoutText = new TextDecoder().decode(stdout);
  const stderrText = new TextDecoder().decode(stderr);

  if (code !== 0) {
    console.error(`Error executing command: ${commandString}`);
    console.error(stderrText);
    throw new Error(`Command failed with code ${code}`);
  }

  console.log(stdoutText.trim());
  return stdoutText;
}

async function createRelease() {
  console.log("--- Starting GitHub Release Process ---");

  const releaseArgs = [
    "release",
    "create",
    TAG,
    "--title",
    RELEASE_NAME,
    "--notes",
    RELEASE_NOTES,
    "--latest",
  ];

  try {
    await runCommand("gh", releaseArgs);
    console.log(`\n🎉 Successfully created release ${TAG}`);
  } catch (error) {
    if (error instanceof Error && error.message.includes("already exists")) {
      console.warn(`⚠️ Release tag ${TAG} already exists.`);
    } else {
      throw error;
    }
  }
}

async function publishJSR() {
  console.log("\n--- Publishing to JSR ---");
  const cmd = new Deno.Command("deno", {
    args: ["publish"],
    stdin: "inherit",
    stdout: "inherit",
    stderr: "inherit",
  });
  const { code } = await cmd.output();
  if (code !== 0) throw new Error("deno publish failed");
  console.log("\n🎉 Successfully published to JSR");
}

await createRelease();
await publishJSR();
