// ------------------------------
// GENERATED BY GOOGLE GEMINI 3.0
// ------------------------------

// --- Configuration ---
const TAG = "v0.1.1";
const RELEASE_NAME = "Version 0.1.1";
const RELEASE_NOTES = "Add ILabelConfig to module exports";
// ---------------------

async function runCommand(command: string, args: string[]): Promise<string> {
  const commandString = `${command} ${args.join(" ")}`;
  console.log(`\n$ ${commandString}`);

  const cmd = new Deno.Command(command, {
    args,
    stdout: "piped",
    stderr: "piped",
  });

  const { code, stdout, stderr } = await cmd.output();

  const stdoutText = new TextDecoder().decode(stdout);
  const stderrText = new TextDecoder().decode(stderr);

  if (code !== 0) {
    console.error(`Error executing command: ${commandString}`);
    console.error(stderrText);
    throw new Error(`Command failed with code ${code}`);
  }

  console.log(stdoutText.trim());
  return stdoutText;
}

async function createRelease() {
  console.log("--- Starting GitHub Release Process ---");

  // Define arguments for gh release command
  const releaseArgs = [
    "release",
    "create",
    TAG,
    "--title",
    RELEASE_NAME,
    "--notes",
    RELEASE_NOTES,
    "--latest",
  ];

  try {
    // Attempt to create the new release
    await runCommand("gh", releaseArgs);
    console.log(
      `\n🎉 Successfully created release ${TAG}`,
    );
  } catch (error) {
    if (error instanceof Error && error.message.includes("already exists")) {
      console.warn(
        `⚠️ Release tag ${TAG} already exists.`,
      );
    } else {
      throw error;
    }
  }
}

createRelease();
